services:
  databasedev:
    image: postgres:17
    container_name: fiap-hack-db-dev
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PORT
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdatadev:/var/lib/postgresql/data
  databaseuserdev:
    image: postgres:17
    container_name: fiap-hack-db-user-dev
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_GATEKEEPER_PORT
    ports:
      - ${POSTGRES_GATEKEEPER_PORT}:5433
    volumes:
      - pgdatauserdev:/var/lib/postgresql-user/data
  rabbitmqdev:
    image: rabbitmq:4-management
    container_name: fiap-hack-rabbitmq-dev
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: rabbitmq-diagnostics ping
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
  rustfs:
    image: rustfs/rustfs:latest
    container_name: fiap-hack-rustfs
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - rustfs_data:/data
      - rustfs_logs:/logs
  local-cognito: 
    image: jagregory/cognito-local:latest
    container_name: cognito-local
    ports:
      - "9229:9229"
    volumes:
      - /app/.cognito 
volumes:
  pgdatadev:
  rustfs_data:
  rustfs_logs:
  local-cognito:
  pgdatauserdev:
