services:
  databasedev:
    image: postgres:17
    container_name: fiap-hack-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdatadev:/var/lib/postgresql/data

  rabbitmqdev:
    image: rabbitmq:4-management
    container_name: fiap-hack-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: rabbitmq-diagnostics ping
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  redisdev:
    image: redis:7-alpine
    container_name: fiap-hack-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rustfs:
    image: rustfs/rustfs:latest
    container_name: fiap-hack-rustfs
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - rustfs_data:/data
      - rustfs_logs:/logs
    restart: unless-stopped

  api:
    image: fiap-hack-api
    container_name: fiap-hack-api
    env_file:
      - .env
    depends_on:
      databasedev:
        condition: service_started
      rabbitmqdev:
        condition: service_healthy
      redisdev:
        condition: service_healthy
      rustfs:
        condition: service_started
    ports:
      - "3000:3000"
    restart: unless-stopped

  video-processor:
    image: fiap-hack-video-processor
    container_name: fiap-hack-video-processor
    env_file:
      - .env
    depends_on:
      databasedev:
        condition: service_started
      rabbitmqdev:
        condition: service_healthy
      rustfs:
        condition: service_started
    restart: unless-stopped

volumes:
  pgdatadev:
  redisdata:
  rustfs_data:
  rustfs_logs:
