services:
  databasedev:
    image: postgres:17
    container_name: fiap-hack-db-dev
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdatadev:/var/lib/postgresql/data
    networks:
      - fiap-network
    restart: unless-stopped

  rabbitmqdev:
    image: rabbitmq:4-management
    container_name: fiap-hack-rabbitmq-dev
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: rabbitmq-diagnostics ping
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - fiap-network
    restart: unless-stopped

  rustfs:
    image: rustfs/rustfs:latest
    container_name: fiap-hack-rustfs
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - rustfs_data:/data
      - rustfs_logs:/logs
    networks:
      - fiap-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: fiap-hack-prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - fiap-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.0.0
    container_name: fiap-hack-grafana
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
      - ./docker/grafana/dashboards/:/var/lib/grafana/dashboards/
    networks:
      - fiap-network
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  pgdatadev:
  rustfs_data:
  rustfs_logs:
  prometheus_data:
  grafana_data:

networks:
  fiap-network:
    driver: bridge
