apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fiap-hack
data:
  LOG_LEVEL: "info"
  NODE_ENV: "production"
  API_PORT: "3000"
  VIDEO_PROCESSOR_PORT: "3000"
  USER_NOTIFIER_PORT: "3000"
  RABBITMQ_URL: "amqp://rabbitmq:5672"
  RABBITMQ_PREFETCH_COUNT: "1"
  RABBITMQ_REQUEUE_ON_ERROR: "true"
  USER_NOTIFIER_SERVICE_QUEUE: "user_notifier_queue"
  GATEKEEPER_URL: "http://gatekeeper:3000"
  REDIS_URL: "redis://redis:6379"
  FS_ENDPOINT_URL: "http://rustfs-svc:9000"
  FS_ENDPOINT_URL_PUBLIC: "http://localhost:9000"
  FS_BUCKET_NAME: "fht-videos-dev"
