apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: fiap-hack
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: fiap_hack_db
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
  FS_ACCESS_KEY_ID: rustfsadmin
  FS_SECRET_ACCESS_KEY: rustfsadmin
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/fiap_hack_db"
