apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: fiap-hack
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: fiap_hack_db
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
  FS_ACCESS_KEY_ID: rustfsadmin
  FS_SECRET_ACCESS_KEY: rustfsadmin
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/fiap_hack_db"
  AWS_REGION: local
  COGNITO_ENDPOINT_URL: "http://cognito-local:9229"
  AWS_ACCESS_KEY_ID: ASIAUO3K34C6WC7OLJWH
  AWS_SECRET_ACCESS_KEY: W2BDvytFnTSXoB4zdcsCpO+P+o7DyXxKmY6A2hwS
  AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjEEcaCXVzLXdlc3QtMiJIMEYCIQCNWzVO+u/bs85wZQ1jJeHtBhItOLN1sXLgk/4No/xgqgIhAKIT5bChyGJJSgMm8EkxUspAjD12zyfIGWPLaIW7CXGdKrICCBAQBBoMMzA2Nzc3NDE1ODY5IgxLOp5HW6j2ZzJ7hfAqjwImHqsiThyWe7VVtOLd00az7GY3FsiDVyKVgOHGoCXUvaUgaY5Z0yT0pNaZqq8HUttshRRZCJvMxW5JPo2/nZ9HDGq16cGaQ6uwOhZP6nprngEuKGRcdjrodKJI8oRCc2r+ZuTS+KvSF4TmZNwnv7pxzqNSqWdO7HLKYRb6sPkFOCCDjzEnEErDU7bhp7/iSdKKy0mgyte/ONFOrk9Zb5qjMkatMARwloHSpcMxh9ZhwiczVdKamuZTHHTlJTqJIBvtPLthMFPT+P6KmKuMOI+aZ8hw5YnkhEsjuX2ZywBTpjfgVEwpTTdXiTP5hAsuWHGY9mLUPe8KpTBjbOBQXrtly/JsNb6SYKXzWNA43RR6MJShm8sGOpwBFsM3GD6C0wPZ5I7S5gQtiQrFgmZ358g99mdAfeO+JDdx4KCAvxfUK5EhjiIkOlrQaFv7eKZoilO45Ma8mMM7KL8M0TpkFrFnJexRmDFt0yC5MzmLHmzph142nK+1U327jfS82rN7ptoE3DCnLATAcFazJyhlx5BKmeKAU9uQd4UL4jNg681t47F0hGBRSOCmluyRyFrWHoV3UXNr
  INTERNAL_SERVICE_API_KEY: "change-me-in-production"